# Example: SQLite to SQLite Migration
source:
  type: "sqlite"
  connection:
    database: "source.db"

target:
  type: "sqlite"
  connection:
    database: "target.db"

migration:
  batch_size: 1000
  rate_limit_delay: 0.1
  max_retries: 3
  timeout: 30

validation:
  strict_mode: true
  data_type_validation: true

logging:
  level: "INFO"
  file: "sqlite_migration.log"
  console: true